spring.application.name=WanderLog
spring.datasource.url=jdbc:h2:./data/mydb;AUTO_SERVER=TRUE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
server.port=9090
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Google Gemini AI Settings
gemini.api.key=AIzaSyAW1rYtQTvdPJGXkptuR1eufMMFO_fgwGM
gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?key=